import json
import pandas as pd
import warnings
from pathlib import Path
import re

tables = json.load(open("input.json"))

rule all:
	input:
		"../samples.json",
		"samples.csv"

rule tab2samples:
	input:
		tables.keys()
	output:
		"../samples.json",
		"samples.csv"
	run:
		cols=["run","sample","experiment","study"]
		out=dict()
		out2=list()
		for f in input:
			fspec=tables[f]
			d=pd.read_csv(f,sep=fspec["delimiter"])
			for i,r in d.iterrows():
				run=r.loc[fspec["run"]]
				other=dict()
				for tt in cols:
					if tt in fspec:
						p=fspec[tt]
						m=re.match(r"^fixed_string::(.+)$",p)
						if m:
							p=m.group(1)
						else:
							p=r.loc[p]
						other[tt]=p
					else: 
						other[tt]=None
				path=fspec["path"].rstrip("/")
				R1=fspec["R1"].format(acc=run)
				R2=fspec["R2"].format(acc=run)
				R1="{p}/{r}".format(p=path,r=R1)
				R2="{p}/{r}".format(p=path,r=R2)
				other["R1"]=R1
				other["R2"]=R2
				data={
					"R1":[R1],
					"R2":[R2]
				}
				if not Path(R1).exists():
					warnings.warn("R1 {f} does not exist!".format(f=R1),category=Warning)
				if not Path(R2).exists():
					warnings.warn("R2 {f} does not exist!".format(f=R2),category=Warning)
				out[run]=data
				out2.append(other)
		with open(output[0], "w") as write_file:
			json.dump(out,write_file,indent=4)
		pd.DataFrame(out2,columns=cols).to_csv(output[1],sep=",",index=False)

