# Path to an uncompressed FASTA file with all transcript sequences.
CDNA: '/nfs/pgsb/projects/Olsen_DEK1/results/global_approach/kallisto/data/cosmoss_V3.3.non_redundant_transcriptome.fasta'

# Path to a folder where intermediate files will be written.
OUT_DIR: 'kallisto'

# Path to a JSON file with samples and their corresponding FASTQ files.
SAMPLES_JSON: 'samples.json'
